### ISSUE TITLE
Tentar usar um conexão para um vhost diferente do padrão, retorna exception

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/async-worker#66]
No #59, implementamos a possibilidade do handler usar a conexão com o Rabbit para publicar mensagens.

Mas se usarmos um vhost diferente vemos uma exception:

```
Traceback (most recent call last):
  File "/home/daltonmatos/.local/share/virtualenvs/asgard-log-ingestor-PbBIkK_u/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/daltonmatos/.local/share/virtualenvs/asgard-log-ingestor-PbBIkK_u/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/daltonmatos/sievegroup/sieve/asgard-log-ingestor/logingestor/routes.py", line 65, in put_msg
    await queue.put(msg, routing_key="test-logger-1", exchange="", vhost="fluentd2")
  File "/home/daltonmatos/sievegroup/sieve/asgard-log-ingestor/vendor/async-worker/asyncworker/rabbitmq/connection.py", line 55, in put
    return await conn.put(body, routing_key, exchange)
  File "/home/daltonmatos/sievegroup/sieve/asgard-log-ingestor/vendor/easyqueue/easyqueue/async_queue.py", line 95, in put
    return await self._channel.publish(payload=payload.encode(),
AttributeError: 'NoneType' object has no attribute 'publish'
```

O que deveríamos fazer é um "auto-connect", assim fica transparente para o handler.

**Comment by diogommartins** [comment]
Essa issue pode ser resolvida com esse PR no easyqueue https://github.com/B2W-BIT/easyqueue/pull/10 e um update de dependência aqui no async-worker

**Comment by daltonmatos** [comment]
Blz. Vamos tentar fechar uma nova versçao do easyqueue, idealmente já incluindo a issue [#20](/B2W-BIT/easyqueue/issues/20), mas se for sem também não tem problema.

**Comment by daltonmatos** [comment]
Done. https://github.com/B2W-BIT/async-worker/pull/59
